### ISSUE TITLE
Reference other cloudlet patterns in blueprint

### ISSUE THREAD

**Issue by robparrott** [huit/nepho#113]
Clearly controversial, but here for reference (excuse the pun).

Allow the user to reference a pattern or hook (i.e. any resource) from another cloudlet via a specified pattern field in the blueprint,  with a notation such as

```
pattern: other-cloudlet :: pattern-name
bootstrap: stdlib :: puppet-bootstrap
```

This will be used in the resolver (in the ResourceManager class) to setup a search path that is within the other cloudlet's directory, and not this one. everything else, in particular data/\* will be local.

**Comment by tfhartmann** [comment]
I'm a little split on this, on one hand I can see it as useful, on the other it adds dependencies in cloudlets. At the moment we don't have a way for cloudlet A to require cloudlet B and ensure that it's installed. Not to mention it makes it more difficult to work on cloudlets since _some_ code may be in your cloudlet, and some may be referenced elsewhere.   So yeah, not sure yet, but just some thoughts.

**Comment by agperson** [comment]
As previously stated, I'm entirely against, in part for the sorts of reasons @tfhartmann stated.

**Comment by tfhartmann** [comment]
@hakamadare do you have any thoughts?

**Comment by hakamadare** [comment]
huh.  i guess i still don't see a problem that this feature would solve, and i think it makes our development work significantly harder (because what if resource `cloudlet1::foo` is only present in `cloudlet1` version 0.2.1 or later, so ok, we permit the specification of `pattern: cloudlet1 (>= 0.2.1) :: pattern-name`, except that oh, its behavior has changed in `cloudlet1` version 1.0.0, so then we permit the specification of `pattern: cloudlet1 (>= 0.2.1, < 1.0.0) :: pattern-name`, and so now we have managed to recreate rubygem hell for ourselves).

i really think that as of right now, the appropriate places to put high-quality, reuse-worthy code are in `nepho` core and in the reference cloudlet.

**Comment by robparrott** [comment]
Again: created for reference purposes.

**Comment by agperson** [comment]
Format 1 has been finalized, so closing this for now.
