### ISSUE TITLE
helpful output after deployment is complete

### ISSUE THREAD

**Issue by hakamadare** [huit/nepho#50]
in an ideal world, i'd like a nepho run to look like this:

```
$ nepho -E production deploy foo
{
    <AWS status stanza>
}
Deployment started: <timestamp>
... <some sort of progress indicator>
Deployment completed: <timestamp>
Deployment status: SUCCESS
Bastion Host:   <hostname>  <ip>
NAT Host:       <hostname>  <ip>

Tier 1 ELB:     <hostname>  <ip>
Tier 1 Hosts:   <hostname>  <ip>
                <hostname>  <ip>
                ...

Tier 2 ELB:     <hostname>  <ip>
Tier 2 Hosts:   <hostname>  <ip>
                <hostname>  <ip>
                ...
$
```

**Comment by tfhartmann** [comment]
:+1:  

What about having the "status out" in yaml so it's easy to scrape and pick up with something else if we need to?

**Comment by robparrott** [comment]
That yaml output should be an option --yaml

**Comment by saperia** [comment]
Without going into details, I think Rob's suggestion is a good one.  I for one, do not know yet how we integrate all this with the larger system you have heard me talk about, if what you folks develop is constructed so that it is flexible with regard to returns -- that can only be a good thing.
/jon

**Comment by hakamadare** [comment]
@tfhartmann output in yaml/json/xml/whatever structured format is way better than my little text table.

**Comment by tfhartmann** [comment]
@robparrott what i mean is rather then use a made up human readable output, lets use yaml as the default since it's already easy to read,  use that as the default rather the create a format from scratch that _isn't_ machine parable.  I'm totally ok with there being multiple formats for the output, or even have something other then yaml as the default, I think I'd just prefer that the default be easy to read _and_ machine parseable.  Does that make sense?

**Comment by agperson** [comment]
I think pretty print should be the default and structured text an option.  Maximize usability out of the box, folks who are processing can easily pass an additional flag.

**Comment by agperson** [comment]
This relates to #133 and #87

**Comment by agperson** [comment]
Partially implemented for AWS in with "nepho stack status" command. #217

**Comment by agperson** [comment]
We are now displaying AWS Outputs, which I think is a good general implementation.  We could get fancier, but then we'd have to worry about a lot of different cases.  Vagrant doesn't really support anything like this, so I think this bug only really targets AWS, and I'm going to close it as "good enough".
